spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #initialization-mode: always
    #data: classpath:/data.sql
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
logging:
  level:
    hu.idevelopment: debug
    org.springframework.web: info
    org.hibernate: error
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
#cors-policies: http://localhost:4200, http://127.0.0.1:4200, http://[::1]:4200